# vim:ft=kitty

font_family      family="Adwaita Mono"
bold_font        auto
italic_font      auto
bold_italic_font auto

cursor_stop_blinking_after 10.0

scrollback_lines 10000

mouse_hide_wait -3.0

enable_audio_bell no

tab_bar_style powerline

map --allow-fallback=shifted,ascii kitty_mod+n new_window_with_cwd
map --allow-fallback=shifted,ascii kitty_mod+t new_tab_with_cwd

map --allow-fallback=shifted,ascii ctrl+alt+p command_palette

map ctrl+alt+1 goto_tab 1
map ctrl+alt+2 goto_tab 2
map ctrl+alt+3 goto_tab 3
map ctrl+alt+4 goto_tab 4
map ctrl+alt+5 goto_tab 5
map ctrl+alt+6 goto_tab 6
map ctrl+alt+7 goto_tab 7
map ctrl+alt+8 goto_tab 8
map ctrl+alt+9 goto_tab 9

## name: Modus Operandi Tinted
## author: Protesilaos Stavrou
## license: GPLv3
## blurb: Highly accessible themes made for GNU Emacs, conforming with the highest
## standard for colour contrast between background and foreground values (WCAG AAA)

# The basic colors
background              #fbf7f0
foreground              #000000
selection_background    #c2bcb5
selection_foreground    #000000

# Cursor colors
cursor                  #d00000
cursor_text_color       #fbf7f0

# kitty window border colors
active_border_color     #193668
inactive_border_color   #9f9f9f

# Tab bar colors
active_tab_background   #c9b8b1
active_tab_foreground   #000000
inactive_tab_background #dfd6cd
inactive_tab_foreground #585858

# The basic 16 colors
# black
color0 #000000
color8 #595959

# red
color1 #a60000
color9 #972500

# green
color2  #006800
color10 #00663f

# yellow
color3  #6f5500
color11 #884900

# blue
color4  #0031a9
color12 #3548cf

# magenta
color5  #721045
color13 #531ab6

# cyan
color6  #005e8b
color14 #005f5f

# white
color7  #a6a6a6
color15 #595959
